disabled_rules:
  - todo
  - force_cast
  - force_try
  - variable_name_min_length
included:
  - Gaston
line_length: 110
type_body_length:
  - 300 # warning
  - 400 # error
variable_name_max_length:
  - 40 # warning
  - 60 # error
